name: heur_single_leap_sp
baseline: single_scale
robot_name: leap_sp
description:

requires:
  task:
    init_source: surface_sample
    scene_source:
      use_object_scale_list: true

overrides:
  suite:
    grasp_types:
      1_right_two:
        object_scale_list: [0.02, 0.03]
      2_right_three:
        object_scale_list: [0.04, 0.06, 0.08]
      3_right_full:
        object_scale_list: [0.11, 0.13, 0.16]
      4_both_three:
        object_scale_list: []
      5_both_full:
        object_scale_list: [0.19, 0.23, 0.26, 0.30]
  manip:
    sim_dual_dummy_arm_leap_sp/tabletop_three.yml:
      seeder_cfg:
        sampling_mode: random_xy_symmetric
    sim_dual_dummy_arm_leap_sp/tabletop_full.yml:
      seeder_cfg:
        sampling_mode: random_xy_symmetric