name: human_leap_sp
baseline: human
robot_name: leap_sp
description:

requires:
  task:
    init_source: human
    scene_source:
      use_object_scale_list: false

overrides:
  suite:
    human_prior: {}
