##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    use_root_pose: False
    dummy_trans_joints: ["ra_TransXJ", "ra_TransYJ", "ra_TransZJ", "la_TransXJ", "la_TransYJ", "la_TransZJ"]
    dummy_rot_joints: ["ra_RotXJ", "ra_RotYJ", "ra_RotZJ", "la_RotXJ", "la_RotYJ", "la_RotZJ"]
    hand_pose_transfer_path: "hand_pose_transfer/dual_dummy_arm_leap_sp.yml"
    grad_group_names: [
      ["ra_TransXJ", "ra_TransYJ", "ra_TransZJ", "ra_RotXJ", "ra_RotYJ", "ra_RotZJ"],
      ["la_TransXJ", "la_TransYJ", "la_TransZJ", "la_RotXJ", "la_RotYJ", "la_RotZJ"],
      ["rh_joint_12", "rh_joint_13", "rh_joint_14", "rh_joint_15",
       "rh_joint_1", "rh_joint_0", "rh_joint_2", "rh_joint_3",
       "rh_joint_5", "rh_joint_4", "rh_joint_6", "rh_joint_7",
       "rh_joint_9", "rh_joint_8", "rh_joint_10", "rh_joint_11"],
      ["lh_joint_12", "lh_joint_13", "lh_joint_14", "lh_joint_15",
       "lh_joint_1", "lh_joint_0", "lh_joint_2", "lh_joint_3",
       "lh_joint_5", "lh_joint_4", "lh_joint_6", "lh_joint_7",
       "lh_joint_9", "lh_joint_8", "lh_joint_10", "lh_joint_11"],
    ]

    urdf_path: "robot/leap_hand/dual_dummy_arm_leap_sp.urdf"
    asset_root_path: "robot/leap_hand"

    base_link: "world"
    ee_link: "rh_palm_lower" # must be the first link in hand_pose_transfer
    link_names: [
      "rh_finger1_tip_center", "rh_finger2_tip_center", "rh_finger3_tip_center", "rh_thumb_tip_center",
      "lh_finger1_tip_center", "lh_finger2_tip_center", "lh_finger3_tip_center", "lh_thumb_tip_center"
    ]
    lock_joints: null
    extra_links: null

    collision_link_names: [
      "rh_palm_lower",
      "rh_mcp_joint", "rh_pip", "rh_dip", "rh_fingertip_base", "rh_fingertip_1",
      "rh_mcp_joint_2", "rh_pip_2", "rh_dip_2", "rh_fingertip_base_2", "rh_fingertip_2",
      "rh_mcp_joint_3", "rh_pip_3", "rh_dip_3", "rh_fingertip_base_3", "rh_fingertip_3",
      "rh_pip_4", "rh_thumb_dip", "rh_thumb_fingertip_base", "rh_thumb_fingertip",
      "lh_palm_lower",
      "lh_mcp_joint", "lh_pip", "lh_dip", "lh_fingertip_base", "lh_fingertip_1",
      "lh_mcp_joint_2", "lh_pip_2", "lh_dip_2", "lh_fingertip_base_2", "lh_fingertip_2",
      "lh_mcp_joint_3", "lh_pip_3", "lh_dip_3", "lh_fingertip_base_3", "lh_fingertip_3",
      "lh_pip_4", "lh_thumb_dip", "lh_thumb_fingertip_base", "lh_thumb_fingertip"
    ]
    collision_spheres: "spheres/dual_dummy_arm_leap_sp.yml"
    collision_sphere_buffer: 0.0
    extra_collision_spheres: {}
    self_collision_ignore: {
      "rh_palm_lower": ["rh_mcp_joint", "rh_mcp_joint_2", "rh_mcp_joint_3", "rh_pip_4", "rh_thumb_dip"],
      "rh_mcp_joint": ["rh_pip"],
      "rh_pip": ["rh_dip"],
      "rh_dip": ["rh_fingertip_base", "rh_fingertip_1"],
      "rh_fingertip_base": ["rh_fingertip_1"],
      "rh_fingertip_1": [],

      "rh_mcp_joint_2": ["rh_pip_2"],
      "rh_pip_2": ["rh_dip_2"],
      "rh_dip_2": ["rh_fingertip_base_2", "rh_fingertip_2"],
      "rh_fingertip_base_2": ["rh_fingertip_2"],
      "rh_fingertip_2": [],

      "rh_mcp_joint_3": ["rh_pip_3"],
      "rh_pip_3": ["rh_dip_3"],
      "rh_dip_3": ["rh_fingertip_base_3", "rh_fingertip_3"],
      "rh_fingertip_base_3": ["rh_fingertip_3"],
      "rh_fingertip_3": [],

      "rh_pip_4": ["rh_thumb_dip"],
      "rh_thumb_dip": ["rh_thumb_fingertip_base"],
      "rh_thumb_fingertip_base": ["rh_thumb_fingertip"],
      "rh_thumb_fingertip": [],

      "lh_palm_lower": ["lh_mcp_joint", "lh_mcp_joint_2", "lh_mcp_joint_3", "lh_pip_4", "lh_thumb_dip"],
      "lh_mcp_joint": ["lh_pip"],
      "lh_pip": ["lh_dip"],
      "lh_dip": ["lh_fingertip_base", "lh_fingertip_1"],
      "lh_fingertip_base": ["lh_fingertip_1"],
      "lh_fingertip_1": [],

      "lh_mcp_joint_2": ["lh_pip_2"],
      "lh_pip_2": ["lh_dip_2"],
      "lh_dip_2": ["lh_fingertip_base_2", "lh_fingertip_2"],
      "lh_fingertip_base_2": ["lh_fingertip_2"],
      "lh_fingertip_2": [],

      "lh_mcp_joint_3": ["lh_pip_3"],
      "lh_pip_3": ["lh_dip_3"],
      "lh_dip_3": ["lh_fingertip_base_3", "lh_fingertip_3"],
      "lh_fingertip_base_3": ["lh_fingertip_3"],
      "lh_fingertip_3": [],

      "lh_pip_4": ["lh_thumb_dip"],
      "lh_thumb_dip": ["lh_thumb_fingertip_base"],
      "lh_thumb_fingertip_base": ["lh_thumb_fingertip"],
      "lh_thumb_fingertip": []
    }
    self_collision_buffer: {
      "rh_palm_lower": 0,
      "rh_mcp_joint": 0,
      "rh_pip": 0,
      "rh_dip": 0,
      "rh_fingertip_base": 0,
      "rh_fingertip_1": 0.002,

      "rh_mcp_joint_2": 0,
      "rh_pip_2": 0,
      "rh_dip_2": 0,
      "rh_fingertip_base_2": 0,
      "rh_fingertip_2": 0.002,

      "rh_mcp_joint_3": 0,
      "rh_pip_3": 0,
      "rh_dip_3": 0,
      "rh_fingertip_base_3": 0,
      "rh_fingertip_3": 0.002,

      "rh_pip_4": 0,
      "rh_thumb_dip": 0,
      "rh_thumb_fingertip_base": 0,
      "rh_thumb_fingertip": 0.002,

      "lh_palm_lower": 0,
      "lh_mcp_joint": 0,
      "lh_pip": 0,
      "lh_dip": 0,
      "lh_fingertip_base": 0,
      "lh_fingertip_1": 0.002,

      "lh_mcp_joint_2": 0,
      "lh_pip_2": 0,
      "lh_dip_2": 0,
      "lh_fingertip_base_2": 0,
      "lh_fingertip_2": 0.002,

      "lh_mcp_joint_3": 0,
      "lh_pip_3": 0,
      "lh_dip_3": 0,
      "lh_fingertip_base_3": 0,
      "lh_fingertip_3": 0.002,

      "lh_pip_4": 0,
      "lh_thumb_dip": 0,
      "lh_thumb_fingertip_base": 0,
      "lh_thumb_fingertip": 0.002
    }

    use_global_cumul: True
    mesh_link_names: [
      "rh_palm_lower",
      "rh_mcp_joint", "rh_pip", "rh_dip", "rh_fingertip_base", "rh_fingertip_1",
      "rh_mcp_joint_2", "rh_pip_2", "rh_dip_2", "rh_fingertip_base_2", "rh_fingertip_2",
      "rh_mcp_joint_3", "rh_pip_3", "rh_dip_3", "rh_fingertip_base_3", "rh_fingertip_3",
      "rh_pip_4", "rh_thumb_dip", "rh_thumb_fingertip_base", "rh_thumb_fingertip",
      "lh_palm_lower",
      "lh_mcp_joint", "lh_pip", "lh_dip", "lh_fingertip_base", "lh_fingertip_1",
      "lh_mcp_joint_2", "lh_pip_2", "lh_dip_2", "lh_fingertip_base_2", "lh_fingertip_2",
      "lh_mcp_joint_3", "lh_pip_3", "lh_dip_3", "lh_fingertip_base_3", "lh_fingertip_3",
      "lh_pip_4", "lh_thumb_dip", "lh_thumb_fingertip_base", "lh_thumb_fingertip"
    ]

    cspace:
      joint_names: [
        "ra_TransXJ", "ra_TransYJ", "ra_TransZJ", "ra_RotXJ", "ra_RotYJ", "ra_RotZJ",
        "la_TransXJ", "la_TransYJ", "la_TransZJ", "la_RotXJ", "la_RotYJ", "la_RotZJ",
        "rh_joint_12", "rh_joint_13", "rh_joint_14", "rh_joint_15",
        "rh_joint_1", "rh_joint_0", "rh_joint_2", "rh_joint_3",
        "rh_joint_5", "rh_joint_4", "rh_joint_6", "rh_joint_7",
        "rh_joint_9", "rh_joint_8", "rh_joint_10", "rh_joint_11",
        "lh_joint_12", "lh_joint_13", "lh_joint_14", "lh_joint_15",
        "lh_joint_1", "lh_joint_0", "lh_joint_2", "lh_joint_3",
        "lh_joint_5", "lh_joint_4", "lh_joint_6", "lh_joint_7",
        "lh_joint_9", "lh_joint_8", "lh_joint_10", "lh_joint_11"
      ]
      retract_config: [
        0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0,
        -0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        -0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
      ]
      null_space_weight: [
        1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
      cspace_distance_weight: [
        1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      ]
      max_jerk: 500.0
      max_acceleration: 15.0
