##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
robot_cfg:
  kinematics:
    use_root_pose: True
    hand_pose_transfer_path: "hand_pose_transfer/leap_sp.yml"

    urdf_path: "robot/leap_hand/leap_sp.urdf"
    asset_root_path: "robot/leap_hand"
    
    base_link: "rh_palm_lower"
    ee_link: "rh_fingertip_1"
    link_names: ['rh_finger1_tip_center', 'rh_finger2_tip_center', 'rh_finger3_tip_center', 'rh_thumb_tip_center']
    lock_joints: null
    extra_links: null

    collision_link_names: ['rh_palm_lower', 
      'rh_mcp_joint', 'rh_pip', 'rh_dip', 'rh_fingertip_base', 'rh_fingertip_1', 
      'rh_mcp_joint_2', 'rh_pip_2', 'rh_dip_2', 'rh_fingertip_base_2', 'rh_fingertip_2',
      'rh_mcp_joint_3', 'rh_pip_3', 'rh_dip_3', 'rh_fingertip_base_3', 'rh_fingertip_3',
      'rh_pip_4', 'rh_thumb_dip', 'rh_thumb_fingertip_base', 'rh_thumb_fingertip']
    collision_spheres: "spheres/leap_sp.yml"
       
    collision_sphere_buffer: 0.0
    extra_collision_spheres: {}
    self_collision_ignore: {
      'rh_palm_lower' : ['rh_mcp_joint', 'rh_mcp_joint_2', 'rh_mcp_joint_3', 'rh_pip_4', 'rh_thumb_dip'],
      'rh_mcp_joint' : ['rh_pip'],
      'rh_pip' : ['rh_dip'],
      'rh_dip' : ['rh_fingertip_base', 'rh_fingertip_1'],
      'rh_fingertip_base': ['rh_fingertip_1'],
      'rh_fingertip_1': [],

      'rh_mcp_joint_2' : ['rh_pip_2'],
      'rh_pip_2': ['rh_dip_2'],
      'rh_dip_2' : ['rh_fingertip_base_2', 'rh_fingertip_2'],
      'rh_fingertip_base_2': ['rh_fingertip_2'],
      'rh_fingertip_2': [],

      'rh_mcp_joint_3' : ['rh_pip_3'],
      'rh_pip_3' : ['rh_dip_3'], 
      'rh_dip_3' : ['rh_fingertip_base_3', 'rh_fingertip_3'],
      'rh_fingertip_base_3': ['rh_fingertip_3'],
      'rh_fingertip_3': [],

      'rh_pip_4' : ['rh_thumb_dip'],
      'rh_thumb_dip' : ['rh_thumb_fingertip_base'],
      'rh_thumb_fingertip_base' : [rh_thumb_fingertip],
      'rh_thumb_fingertip': []
    }
    self_collision_buffer: {
      'rh_palm_lower' : 0,
      'rh_mcp_joint' : 0,
      'rh_pip' : 0,
      'rh_dip' : 0,
      'rh_fingertip_base': 0,
      'rh_fingertip_1': 0.002,

      'rh_mcp_joint_2' : 0,
      'rh_pip_2': 0,
      'rh_dip_2' : 0,
      'rh_fingertip_base_2': 0,
      'rh_fingertip_2' : 0.002,

      'rh_mcp_joint_3' : 0,
      'rh_pip_3' : 0, 
      'rh_dip_3' : 0,
      'rh_fingertip_base_3': 0,
      'rh_fingertip_3': 0.002,

      'rh_pip_4' : 0,
      'rh_thumb_dip' : 0,
      'rh_thumb_fingertip_base' : 0,
      'rh_thumb_fingertip': 0.002
    }

    use_global_cumul: True
    mesh_link_names:
      [
        'rh_palm_lower' ,

        'rh_mcp_joint' ,
        'rh_pip' ,
        'rh_dip' ,
        'rh_fingertip_base',
        'rh_fingertip_1',

        'rh_mcp_joint_2' ,
        'rh_pip_2',
        'rh_dip_2' ,
        'rh_fingertip_base_2',
        'rh_fingertip_2',

        'rh_mcp_joint_3' ,
        'rh_pip_3' , 
        'rh_dip_3' ,
        'rh_fingertip_base_3',
        'rh_fingertip_3',

        'rh_pip_4' ,
        'rh_thumb_dip' ,
        'rh_thumb_fingertip_base',
        'rh_thumb_fingertip'
      ]

    cspace:
      joint_names: ['rh_joint_12', 'rh_joint_13', 'rh_joint_14', 'rh_joint_15', 
                    'rh_joint_1', 'rh_joint_0', 'rh_joint_2', 'rh_joint_3', 
                    'rh_joint_5', 'rh_joint_4', 'rh_joint_6', 'rh_joint_7',
                    'rh_joint_9', 'rh_joint_8', 'rh_joint_10', 'rh_joint_11']
      # retract_config: [0.0, -1.0471975511965976, 1.3089969389957472, 1.3089969389957472, 1.5707963267948966, 0.0, 0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]
      retract_config: [-0.5, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]
      # retract_config: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0] # List[float]
      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
      max_jerk: 500.0
      max_acceleration: 15.0
